# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9d828f2e7cf5543ef756541787d701d98e2b9de42e7717d3cf9dc7a8bac0968793f538eb13f7097cc6f25fc4462441eb6b1dc4074ce0a1b931f27515cbfdee8

test:
  secret_key_base: fb840f65751cefc98636f11ca0dc90898d30862a90380b6510a899abc9e28b8b887846b3cc1a5bfa78020019cf319ecad57ef6370adfd1bdbfd7e061adf167dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
